# Generated by Django 5.0 on 2025-10-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('trend_score', models.IntegerField(default=0, help_text='Higher means more trending nearby')),
                ('place', models.CharField(blank=True, max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='movies.movie')),
            ],
            options={
                'ordering': ['-trend_score'],
            },
        ),
    ]
