# Generated by Django 5.0 on 2025-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movielocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielocation',
            name='purchase_count',
            field=models.IntegerField(default=0, help_text='Number of purchases at this location'),
        ),
    ]
